### ISSUE TITLE
你好，运行项目报错

### ISSUE THREAD

**Issue by JserJser** [falseLuffy/react-native-develope#1]
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/reactNativeDemo.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/reactNativeDemo.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

    at checkExecSyncError (child_process.js:616:11)
    at Object.execFileSync (child_process.js:634:13)
    at Promise.then (/Users/liuchang/517box/react-native-develope/node_modules/react-native/local-cli/runIOS/runIOS.js:208:5)

**Comment by falseLuffy** [comment]
我刚刚试了一下，并没有发生你这样的错误，安装完依赖后，运行正常。
运行前先安装完xcode或Android Studio。
